FROM openjdk:8-jre

WORKDIR /usr/src

ADD classes target/classes
ADD dependency target/dependency

CMD java -Xmx2048m -cp "target/dependency/*:target/classes/"    \
    -Drestolino.packageprefix=com.github.onsdigital.zebedee.api \
    -Drestolino.classes=target/classes                          \
    -javaagent:target/dependency/aws-opentelemetry-agent-1.30.0.jar \
    -Dotel.propagators=tracecontext,baggage \
    -Dotel.service.name=zebedee \
    com.github.davidcarboni.restolino.Main
