#!/bin/bash

#############################################################
###                                                       ###
### Generated by github.com/ONSdigital/dp-zebedee-content ###
###                                                       ###
#############################################################

# Sets the root Zebedee directory required to run Zebedee in publishing / CMS mode.
export zebedee_root="${zebedee_root:-/Users/sandypadmanabhan/development/ons/zebedee-content}"

# Zebedee runs by default on port :8082
export PORT="${PORT:-8082}"

export JAVA_OPTS=" -Xmx1204m -Xdebug -Xrunjdwp:transport=dt_socket,address=8002,server=y,suspend=n"

# Restolino configuration
export RESTOLINO_STATIC="src/main/resources/files"
export RESTOLINO_CLASSES="zebedee-cms/target/classes"
export PACKAGE_PREFIX=com.github.onsdigital.zebedee

# If enabled on start up Zebedee will attempt to connect to the audit database. Generally this isn't required for dev
# local unless you require "working" audit logging it can be disabled. If enabled=false then a NOP database stub is used
# instead allowing the app to start without a database connection.
export audit_db_enabled=false

# File contains connection parameters for the audit and collection history database. Can be ignored if audit_db_enabled=false
source ./export-default-env-vars.sh

# Pretty format JSON log output
export FORMAT_LOGGING=true

#####################################
###                               ###
### CMD config (dev local values) ###
###                               ###
#####################################

# feature flag to enabled/disabled the CMD features in Zebedee default to enabled
export ENABLE_DATASET_IMPORT="${ENABLE_DATASET_IMPORT:-true}"

# Feature flag to enable CMD authorization features.
export ENABLE_PERMISSIONS_AUTH="${ENABLE_PERMISSIONS_AUTH:-true}"

# the dataset API url set default if not already set
export DATASET_API_URL="${DATASET_API_URL:-http://localhost:22000}"

# the dataset API authentication token set default if not already set
export DATASET_API_AUTH_TOKEN="${DATASET_API_AUTH_TOKEN:-FD0108EA-825D-411C-9B1D-41EF7727F465}"

# Zebedee's authentication token for communicating with the dataset API set default if not already set
export SERVICE_AUTH_TOKEN="${SERVICE_AUTH_TOKEN:-fc4089e2e12937861377629b0cd96cf79298a4c5d329a2ebb96664c88df77b67}"

#
# Compile and run
#
mvn clean package dependency:copy-dependencies -Dmaven.test.skip=true -Dossindex.skip=true && \
java $JAVA_OPTS \
 -Dlogback.configurationFile=zebedee-cms/target/classes/logback.xml \
 -Ddb_audit_url=$db_audit_url \
 -Daudit_db_enabled=$audit_db_enabled \
 -Ddb_audit_username=$db_audit_username \
 -Ddb_audit_password=$db_audit_password \
 -Drestolino.files=$RESTOLINO_STATIC \
 -Drestolino.files=$RESTOLINO_STATIC \
 -Drestolino.classes=$RESTOLINO_CLASSES \
 -Drestolino.packageprefix=$PACKAGE_PREFIX \
 -DSTART_EMBEDDED_SERVER=N \
 -cp "zebedee-cms/target/classes:zebedee-cms/target/dependency/*" \
 com.github.davidcarboni.restolino.Main

