package com.github.onsdigital.zebedee.data.processing;

import com.github.davidcarboni.cryptolite.Random;
import com.github.onsdigital.zebedee.content.page.base.Page;
import com.github.onsdigital.zebedee.content.page.base.PageDescription;
import com.github.onsdigital.zebedee.content.page.base.PageType;
import com.github.onsdigital.zebedee.content.page.statistics.data.timeseries.TimeSeries;
import com.github.onsdigital.zebedee.content.partial.Link;
import com.github.onsdigital.zebedee.data.framework.DataPagesGenerator;
import com.github.onsdigital.zebedee.data.framework.DataPagesSet;
import com.github.onsdigital.zebedee.data.importing.TimeseriesUpdateCommand;
import com.github.onsdigital.zebedee.exceptions.NotFoundException;
import com.github.onsdigital.zebedee.exceptions.ZebedeeException;
import com.github.onsdigital.zebedee.reader.ContentReader;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Optional;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotEquals;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;

/**
 * DataProcessor is the workhorse of the Data Publisher
 *
 * It combines
 *  - a timeseries generated by Brian
 *  - any existing version of this timeseries
 *  - a data landing page
 *  - a timeseries dataset page
 *
 *
 */
public class DataProcessorTest {

    @Mock
    private DataIndex dataIndex;

    @Mock
    private ContentReader publishedReader;

    private DataPagesGenerator generator;
    private DataPublicationDetails exampleDataPublication;
    private TimeSeries exampleTimeSeries;

    /**
     * Setup common test data and mocks.
     *
     * @throws Exception
     */
    @Before
    public void setUp() throws Exception {
        MockitoAnnotations.openMocks(this);

        generator = new DataPagesGenerator();

        // Generate an example set of time series dataset pages with some custom metadata
        DataPagesSet dataPagesSet = generator.generateDataPagesSet("dataprocessor", "thedatasetid", 2015, 2, "file.csdb");
        exampleDataPublication = new DataPublicationDetails(dataPagesSet.timeSeriesDataset, dataPagesSet.datasetLandingPage, dataPagesSet.fileUri);
        setRandomContact(exampleDataPublication.landingPage);
        exampleDataPublication.landingPage.getDescription().setNextRelease(Random.id());
        exampleDataPublication.landingPage.getDescription().setReleaseDate(new Date());
        List<Link> relatedDocs = new ArrayList<>();
        relatedDocs.add(new Link(URI.create("/testing/123")));
        exampleDataPublication.landingPage.setRelatedDatasets(relatedDocs);

        // Extract an example time series and set some further custom metadata
        exampleTimeSeries = dataPagesSet.timeSeriesList.get(0);
        exampleTimeSeries.getDescription().setUnit(Random.id());
        exampleTimeSeries.getDescription().setPreUnit(Random.id());
        exampleTimeSeries.getDescription().setNationalStatistic(true);
    }

    @Test
    public void getDatasetBasedUriForTimeseries_givenUnindexed_returnsExpectedUrl() {
        // Given
        // A timeseries from a reviewed dataset that is unindexed
        when(dataIndex.getUriForCdid(eq(exampleTimeSeries.getCdid()))).thenReturn(null);

        // When
        // we get the uri for a timeseries with the dataset ID included
        String actual = new DataProcessor().getDatasetBasedUriForTimeseries(exampleTimeSeries, exampleDataPublication, dataIndex);

        // Then
        // we get the expected URI with correct dataset ID
        assertEquals(exampleTimeSeries.getUri().toString(), actual);
    }

    @Test
    public void getDatasetBasedUriForTimeseries_givenIndexed_returnsExpectedUrl() {
        // Given
        // A timeseries from our reviewed dataset
        when(dataIndex.getUriForCdid(eq(exampleTimeSeries.getCdid()))).thenReturn(exampleTimeSeries.getUri().resolve(".").toString());

        // When
        // we get the uri for a timeseries with the dataset ID included
        String actual = new DataProcessor().getDatasetBasedUriForTimeseries(exampleTimeSeries, exampleDataPublication, dataIndex);

        // Then
        // we get the expected URI with correct dataset ID
        assertEquals(exampleTimeSeries.getUri().toString(), actual);
    }


    @Test
    public void initialTimeseries_givenNewTimeseries_returnsEmptyTimeseries() throws IOException, URISyntaxException, ZebedeeException {
        // Given
        // A new time series that does not exist
        when(dataIndex.getUriForCdid(eq(exampleTimeSeries.getCdid()))).thenReturn(null);
        when(publishedReader.getContent(eq(exampleTimeSeries.getUri().toString()))).thenThrow(new NotFoundException("not here"));

        // When
        // we get the initialTimeseries
        TimeSeries initial = new DataProcessor().initialTimeseries(exampleTimeSeries, publishedReader, exampleDataPublication, dataIndex);

        // Then
        // we expect it to be a skeleton timeseries
        assertEquals(PageType.TIMESERIES, initial.getType());
        assertEquals(0, initial.years.size());
        assertEquals(0, initial.months.size());
        assertEquals(0, initial.quarters.size());
    }

    @Test
    public void initialTimeseries_givenExistingTimeseries_returnsCurrentTimeseries() throws IOException, URISyntaxException, ZebedeeException {
        // Given
        // A time series that already exists
        when(dataIndex.getUriForCdid(eq(exampleTimeSeries.getCdid()))).thenReturn(exampleTimeSeries.getUri().resolve(".").toString());
        when(publishedReader.getContent(eq(exampleTimeSeries.getUri().toString()))).thenReturn(exampleTimeSeries);

        // When
        // we get the initialTimeseries
        TimeSeries initial = new DataProcessor().initialTimeseries(exampleTimeSeries, publishedReader, exampleDataPublication, dataIndex);

        // Then
        // we expect it to be the published timeseries complete with existing data
        assertEquals(PageType.TIMESERIES, initial.getType());
        assertEquals(exampleTimeSeries.getUri(), initial.getUri());
        assertNotEquals(0, initial.years.size());
        assertNotEquals(0, initial.months.size());
        assertNotEquals(0, initial.quarters.size());
    }

    @Test
    public void syncLandingPageMetadata_correctlySyncsMetadata() throws URISyntaxException {
        // Given
        // A new timeseries
        TimeSeries newTimeSeries = new TimeSeries();

        // When
        // process the timeseries
        TimeSeries synced = new DataProcessor().syncLandingPageMetadata(newTimeSeries, exampleDataPublication);

        // Then
        // the timeseries should have the metadata synced from the landing page
        assertEquals(exampleDataPublication.landingPage.getDescription().getContact().getName(), synced.getDescription().getContact().getName());
        assertEquals(exampleDataPublication.landingPage.getDescription().getContact().getEmail(), synced.getDescription().getContact().getEmail());
        assertEquals(exampleDataPublication.landingPage.getDescription().getContact().getTelephone(), synced.getDescription().getContact().getTelephone());
        assertEquals(exampleDataPublication.landingPage.getDescription().getContact().getOrganisation(), synced.getDescription().getContact().getOrganisation());
        assertEquals(exampleDataPublication.landingPage.getDescription().getNextRelease(), synced.getDescription().getNextRelease());
        assertEquals(exampleDataPublication.landingPage.getDescription().getReleaseDate(), synced.getDescription().getReleaseDate());
        assertEquals(exampleDataPublication.landingPage.getDescription().getDatasetId(), synced.getDescription().getDatasetId());
        assertEquals(exampleDataPublication.landingPage.getUri(), synced.getDescription().getDatasetUri());
        assertEquals(exampleDataPublication.landingPage.getUri(), synced.getRelatedDatasets().get(0).getUri());
        assertEquals(exampleDataPublication.landingPage.getRelatedDocuments(), synced.getRelatedDocuments());
    }

    @Test
    public void syncTimeSeriesMetadata_correctlySyncsMetadata() {
        // Given
        // A new timeseries
        TimeSeries newTimeSeries = new TimeSeries();
        newTimeSeries.setDescription(new PageDescription());

        // When
        // process the timeseries
        TimeSeries synced = new DataProcessor().syncTimeSeriesMetadata(newTimeSeries, exampleTimeSeries);

        // Then
        // the timeseries should have the metadata synced from the other time series
        assertEquals(exampleTimeSeries.getDescription().getCdid(), synced.getDescription().getCdid());
        assertEquals(exampleTimeSeries.getDescription().getTitle(), synced.getDescription().getTitle());
        assertEquals(exampleTimeSeries.getDescription().getDate(), synced.getDescription().getDate());
        assertEquals(exampleTimeSeries.getDescription().getNumber(), synced.getDescription().getNumber());
    }

    @Test
    public void processTimeseries_overExistingTimeSeries_persistsManualSetFields() throws ParseException, URISyntaxException, ZebedeeException, IOException {
        // Given
        // A previously published time series dataset with distinct manual metadata and a new time series dataset being imported
        DataPagesSet newPageSet = generator.generateDataPagesSet("dataprocessor", "thedatasetid", 2016, 2, "");
        DataPublicationDetails newDataPublication = new DataPublicationDetails(newPageSet.timeSeriesDataset, newPageSet.datasetLandingPage, newPageSet.fileUri);
        TimeSeries newSeries = newPageSet.timeSeriesList.get(0);

        when(dataIndex.getUriForCdid(eq(newSeries.getCdid()))).thenReturn(exampleTimeSeries.getUri().resolve(".").toString());
        when(publishedReader.getContent(eq(newSeries.getUri().toString()))).thenReturn(exampleTimeSeries);

        // When
        // process the importing dataset
        TimeSeries processed = new DataProcessor().processTimeseries(publishedReader, newDataPublication, newSeries, dataIndex);

        // Then
        // we expect the manual data to be persisted
        assertEquals(exampleTimeSeries.getDescription().getUnit(), processed.getDescription().getUnit());
        assertEquals(exampleTimeSeries.getDescription().getPreUnit(), processed.getDescription().getPreUnit());
        assertEquals(exampleTimeSeries.getDescription().isNationalStatistic(), processed.getDescription().isNationalStatistic());
    }

    @Test
    public void processTimeseries_withUpdateCommands_updatesTitles() throws IOException, ZebedeeException, URISyntaxException, ParseException {
        // Given
        // We publish a timeseries with update commands to update the title.
        String newTitle = "The new title from update command.";

        Optional<TimeseriesUpdateCommand> command = Optional.of(new TimeseriesUpdateCommand(exampleTimeSeries.getCdid(), exampleTimeSeries.getDescription().getDatasetId(), newTitle));

        when(dataIndex.getUriForCdid(eq(exampleTimeSeries.getCdid()))).thenReturn(exampleTimeSeries.getUri().resolve(".").toString());
        when(publishedReader.getContent(eq(exampleTimeSeries.getUri().toString()))).thenReturn(exampleTimeSeries);

        // When
        // we run a process
        DataProcessor processor = new DataProcessor();
        processor.processTimeseries(publishedReader, exampleDataPublication, exampleTimeSeries, dataIndex, command);

        // Then
        // we expect the title to be that of the update command.
        assertEquals(newTitle, processor.getTimeSeries().getDescription().getTitle());
    }

    /**
     * Helper method
     */
    private void setRandomContact(Page page) {
        page.getDescription().getContact().setEmail(Random.id());
        page.getDescription().getContact().setName(Random.id());
        page.getDescription().getContact().setOrganisation(Random.id());
        page.getDescription().getContact().setTelephone(Random.id());
    }
}
